### PR TITLE
Updating DDL to include era tables

### PR DESCRIPTION
**Pull request by burrowse**
https://github.com/PEDSnet/Data_Models/issues/296

### CODE REVIEW

**Comment by burrowse** [comment]
Please review @aaron0browne @murphyke

**Comment by murphyke** [comment]
@burrowse The new tables need to be added to the definitions/tables.csv file. I think we can improve the automatic testing that happens when a PR is submitted to this repo. I can look at that.

It is possible to test data models changes yourself prior to submitting a PR (or as part of reviewing a PR). The way I noticed this problem was by running the [data-models service](https://github.com/chop-dbhi/data-models-service) locally and feeding it the source repo URL (`data-models -repo https://github.com/burrowse/data-models`). In this case the problem was indicated by some warnings that the service produced when it parsed the source files, but you can also browse http://127.0.0.1:8123 to make sure your changes look good. In particular, you can try the compare/differences method documented on the landing page.

/cc @eceowl

**Comment by murphyke** [comment]
Wow, @burrowse you were quick to install and use the data-models service for your own testing. @eceowl, if tables have already been created using the old version of the DDL but not been completely processed (transformed, etc), then you will have to apply the new creation DDL on those pre-existing schemas (in order to create the new tables) *before* proceeding with other steps like loading or transformation. The automatic creation of indexes, constraints, and transformations will use the new DDL, so the new tables will have to exist.

**Comment by eceowl** [comment]
Okay sounds good to me.

**Comment by penningtonj** [comment]
What's an era table?

On Jan 11, 2017, at 11:57 AM, Kevin Murphy <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged #153<https://github.com/chop-dbhi/data-models/pull/153>.

-

**Comment by murphyke** [comment]
@penningtonj These tables won't be populated by PEDSnet right now, but they are required by the Achilles tool .... They are for holding inferred periods of time. E.g. `drug_era` would hold a range of time that a patient was inferred to be taking a particular medication, based on dates and amounts of prescriptions.

**Comment by burrowse** [comment]
Thank you @murphyke !!

**Pull request merged**
