### PR TITLE
Add version 2.6 to DDL generator

### PR DESCRIPTION
**Pull request by burrowse**
Please review and commit @murphyke @aaron0browne @eceowl

Output from data-models-service revealed no errors....
Cloning into 'data-models/github.com/burrowse/data-models'...
remote: Counting objects: 5364, done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 5364 (delta 41), reused 85 (delta 41), pack-reused 5279
Receiving objects: 100% (5364/5364), 9.03 MiB | 1.69 MiB/s, done.
Resolving deltas: 100% (3377/3377), done.

### CODE REVIEW

**Comment by aaron0browne** [comment]
👍 

Put the turn signal on because we're about to *merge!*

**Comment by burrowse** [comment]
Thank you!!

**Comment by aaron0browne** [comment]
Looks like the data models service already picked it up: https://data-models-service.research.chop.edu/models/pedsnet/2.6.0

**Comment by aaron0browne** [comment]
I'm working on getting data models sqlalchemy updated. Hopefully tomorrow.

**Comment by burrowse** [comment]
@aaron0browne Okay, awesome! Thanks!

**Comment by aaron0browne** [comment]
Updated!

**Pull request merged**
