### PR TITLE
Merging in v2.1 Changes

### PR DESCRIPTION
**Pull request by burrowse**
I created a v2.1 folder, I did not change any of the read me documents.

### CODE REVIEW

**Comment by burrowse** [comment]
@aaron0browne @bruth Can you review? Is the format consistent with what you would expect?

**Comment by bruth** [comment]
I will review shortly.

**Comment by bruth** [comment]
The version field in the [location definition](https://github.com/chop-dbhi/data-models/pull/98/files#diff-44c67e383c632299d55a13dc92098a3d) and [measurement schema](https://github.com/chop-dbhi/data-models/pull/98/files#diff-7550a6b84c5e991f38139be7ad423cb7) files need to be updated for `v2.1`.

I also noticed most of the operational tables (`concept_*`, etc.) contain the omop version, however this exists in the `v2` folder as well. We will do an update on those items (including the ones here) in a subsequent PR.

**Comment by burrowse** [comment]
Thanks @bruth. I updated the location and measurement files. 

I noticed that the concept tables contained omop v5 but I thought that was intentional so I followed suit for v2.1.

**Comment by bruth** [comment]
Great. Can you please squash the commits before I merge?

**Comment by bruth** [comment]
Did you intend to close this? Do you know you can force push squash changes to the same branch?

**Pull request merged**
