### PR TITLE
Updating drug exposure frequency column data type

### PR DESCRIPTION
**Pull request by burrowse**

### CODE REVIEW

**Comment by aaron0browne** [comment]
Can you please remove the redundant denominator_value definitions and schemas from your branch and squash this down to one commit?

**Comment by burrowse** [comment]
Looks like the checks pass and there are no conflicts. Okay to merge?

**Comment by aaron0browne** [comment]
Let me quickly review the output ddl for any unexpected differences and then I'll merge.

**Comment by aaron0browne** [comment]
LGTM, no unexpected DDL changes. Merging.

**Pull request merged**
