### PR TITLE
Refine pedsnet and omop definitions

### PR DESCRIPTION
**Pull request by aaron0browne**
Some from errors thrown in creating the DDL generation tool, others from a review of official DDL files in the PEDSnet/Data_Models and OHDSI/CommonDataModels repos.

### CODE REVIEW

**Comment by bruth** [comment]
This is a beast. It is beautiful.

**Comment by aaron0browne** [comment]
@bruth It doesn't appear that the service endpoint has updated to include these edits... Can you redeploy and/or check on the automatic deploy?

**Comment by bruth** [comment]
I am looking into it.

**Comment by bruth** [comment]
The service provider is using Docker 1.5 and the backwards compatibility broke with 1.6 which is what Docker Hub is using..

**Comment by bruth** [comment]
I am in the process of trying there private registry.

**Comment by bruth** [comment]
And we are back: http://data-models.origins.link I am managing my own Docker host for the time being.

**Pull request merged**
