### PR TITLE
Creating version 2.8 of PEDSnet data model

### PR DESCRIPTION
**Pull request by burrowse**
https://github.com/PEDSnet/Data_Models/issues/339
https://github.com/PEDSnet/Data_Models/issues/337

### CODE REVIEW

**Comment by burrowse** [comment]
Tested changes locally, no errors. @aaron0browne @murphyke Please review and merge if it looks good.

```
burrowse$ data-models-service https://github.com/chop-dbhi/data-models/pull/176
INFO[0000] Listening on 127.0.0.1:8123...               
Cloning into '/Users/burrowse/Documents/data-models/pedsnet/data-models/github.com/chop-dbhi/data-models'...
remote: Counting objects: 5467, done.
remote: Total 5467 (delta 0), reused 0 (delta 0), pack-reused 5467
Receiving objects: 100% (5467/5467), 9.03 MiB | 3.10 MiB/s, done.
Resolving deltas: 100% (3495/3495), done.
```

**Comment by murphyke** [comment]
@burrowse Hi, the CircleCI tests are succeeding, which means that in addition to the base data-models-service, the data-models-sqlalchemy service also didn't notice a problem.

So I will merge it. But I notice you are adding 2.7 and 2.8 at the same time. Why is that, just out of curiosity?

**Comment by burrowse** [comment]
@murphyke I'm not sure why 2.7 is coming in at the same time. I only made changes to v2.8 today

**Comment by murphyke** [comment]
OK, you just didn't base your new changes off the upstream chop-dbhi/data-models master branch. After each version, you should make sure to get the latest chop-dbhi/data-models master branch as your master. It would probably be easier if you made feature branches in your repo (e.g. `v2.8`), PR'd them, and after the merge into chop-dbhi/data-models, threw away your branch and updated your master branch from the upstream.

E.g.:
```
git remote add upstream https://github.com/chop-dbhi/data-models.git
git fetch upstream
git checkout master  # This is your master, in case you're not already on it.
git merge upstream/master  # Bring the latest changes from the remote into your master
```

Or you might choose to just re-fork for each version.

**Comment by burrowse** [comment]
@murphyke Got it, that makes sense. Should I re-do that then?

**Comment by murphyke** [comment]
No, you're good for now. I will merge it.

**Pull request merged**
