### PR TITLE
Fix precision/scale errors in pcornet v3

### PR DESCRIPTION
**Pull request by aaron0browne**
Signed-off-by: Aaron Browne <aaron0browne@gmail.com>

### CODE REVIEW

**Comment by aaron0browne** [comment]
@burrowse Once the CircleCI check completes, I'll pull the DDL that was output and post it here so you can test it.

**Comment by aaron0browne** [comment]
[dms_issue-132_54_6bd990e5_pcornet_3.0_postgres_ddl.txt](https://github.com/chop-dbhi/data-models/files/142858/dms_issue-132_54_6bd990e5_pcornet_3.0_postgres_ddl.txt)

**Comment by burrowse** [comment]
The new DDL in the text file contains the following in the first line: `# pcornet 3.0.0 postgresql ddl`
Skipping that first line the DDL script completed successfully.

**Comment by aaron0browne** [comment]
OK, that line is just a part of the archive format, so it won't show up in the web service. I'll merge the changes. I already checked that no unintended DDL changes were included. ...just realized I need to increment the version number. I'll do that and THEN merge.

**Comment by burrowse** [comment]
Okay, great!

**Pull request merged**
