### PR TITLE
OMOP v4 and PEDSnet v1 constraints, indexes, and references

### PR DESCRIPTION
**Pull request by bruth**
See #17

### CODE REVIEW

**Comment by bruth** [comment]
@aaron0browne This is still a work in progress since there are likely missing or incorrect fields. I am in the process of writing a validator which compares the references, indexes, and constraints against the definitions to see if there are any mismatches. That being said, please take a quick look to see if there are any obvious issues.

**Comment by bruth** [comment]
> I am in the process of writing a validator which compares the references, indexes, and constraints against the definitions to see if there are any mismatches.

I found quite a few mismatches, so I will be updating these shortly.

**Comment by bruth** [comment]
@aaron0browne I am going to merge this so it does not result in conflicts later unless you have something to say about it.

**Comment by aaron0browne** [comment]
Merge!

**Pull request merged**
