### PR TITLE
Issue 257

### PR DESCRIPTION
**Pull request by burrowse**
Request to make the change to add death_cause_id to the death table as the primary key

### CODE REVIEW

**Comment by aaron0browne** [comment]
Shouldn't this be a new data model version if we are adding a new field? i.e.: v2.3? Also, you should add an entry in the not nulls file for this PK.

**Comment by burrowse** [comment]
@aaron0browne Yeah, I wanted to check in with you about that. I'll make the changes for a new version then.

**Comment by aaron0browne** [comment]
Great!

**Comment by burrowse** [comment]
@aaron0browne Will open a new pull request.

**Pull request closed without merging**
