### PR TITLE
Uploading new measurement tables

### PR DESCRIPTION
**Pull request by burrowse**

### CODE REVIEW

**Comment by murphyke** [comment]
Hi Evanette,

The CircleCI test is failing. The new tables are not listed in models.csv. Also, the other error is:

time="2018-02-07T21:10:55Z" level=warning msg="refs (/opt/repos/github.com/burrowse/data-models/pedsnet-split/v2.8:measurement_organism): no source field `measurement_id`".

Finally, the `pedsnet-split` PR is defining model `pedsnet`, version `2.8.0`. I think the model should be different, e.g. `pedsnet-split` to distinguish it from the main model.

**Comment by burrowse** [comment]
@murphyke Thanks for the review! I have made those changes.

**Comment by murphyke** [comment]
At CircleCI, in Artifacts/logs/dms.log, I'm seeing:

time="2018-02-08T15:33:26Z" level=error msg="model (/opt/repos/github.com/burrowse/data-models/pedsnet/v2.8/models.csv): error reading models files"
time="2018-02-08T15:33:26Z" level=warning msg="refs (/opt/repos/github.com/burrowse/data-models/pedsnet-split/v2.8:measurement_organism): no source field `measurement_id`"

**Comment by murphyke** [comment]
The CircleCI build is clean! Shall I merge?

**Comment by burrowse** [comment]
@murphyke Yes! And then we can merge the other PR after? I built this one off of master as opposed to the other feature branch.

**Pull request merged**
