### PR TITLE
Add examples for writing data to CSV files

### LINKED ISSUE #83: Link to examples of CSV libraries for common languages and systems
This specifically applies to writing CSV files to ensure producers of data files are using a well established library rather than trying to roll there own implementation (which is very error-prone).

### PR DESCRIPTION
**Pull request by bruth**
Fix #83 

Signed-off-by: Byron Ruth <b@devel.io>

### CODE REVIEW

**Comment by bruth** [comment]
@chop-dbhi/data-models My goal with this is to provide examples of writing CSV data in various languages. Please add examples for languages you are familiar with. The initial set target common enterprise languages:

- Python
- Java
- .Net
- PL/pgSQL
- Oracle SQL
- MSSQL

**Comment by bruth** [comment]
Potential for Oracle? http://dba.stackexchange.com/questions/1479/how-can-i-unload-oracle-database-tables-into-a-csv-files

**Comment by murphyke** [comment]
Oracle (nor SQL*Plus) has no built-in CSV export feature, but one option is SQLCL, a brand-new command-line client associated with SQL Developer.  I personally haven't used SQLCL, but I would if I were using Oracle.  I *have* used the SQL Developer GUI to export to CSV, which can't be automated, but at least you can reliably create CSV files with it.  Its export default is 'INSERTS', but you can change this to 'CSV'.  All text fields are wrapped in quotes (even NULL values, because NULL and empty string are treated the same in Oracle), and no numeric fields are wrapped in quotes.  Quotes within fields are escaped via doubling.  Newlines within fields are included in the output (as with PostgreSQL).  I imagine SQLCL might work in the same way.  SQLCL can also export in JSON format.

**Comment by bruth** [comment]
> Oracle (nor SQLPlus) has no built-in CSV export feature

My oh my.

Are there particular sites that have more issues than others? Do we know the tech stacks for them? Can you write a quick example using SQLCL?

**Comment by aaron0browne** [comment]
> All text fields are wrapped in quotes (even NULL values, because NULL and empty string are treated the same in Oracle)

Wow...

**Comment by murphyke** [comment]
Added Oracle example

**Comment by bruth** [comment]
This is sufficient for now.

**Pull request merged**
